### ISSUE TITLE
Cannot find entry file index

### ISSUE THREAD

**Issue by sinevitch** [GeekyAnts/native-base-example-rnrf#2]
# **Issue Description**
Cannot find entry file index
I use all your code
![image](https://user-images.githubusercontent.com/35930695/38500225-780b43ec-3c12-11e8-9feb-6cad0d805cfc.png)

![image](https://user-images.githubusercontent.com/35930695/38500264-950f7972-3c12-11e8-93f2-e32504879136.png)

**index.ios.js**
```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
} from 'react-native';
import App from './src/App.js';

export default class RnrfExample extends Component {
  render() {
    return (
      <App />
    );
  }
}

AppRegistry.registerComponent('RnrfExample', () => RnrfExample);
```

---
### Environment
* React Native version: "0.54.0",
* Platform(s) : Xcode
* Device info : iPhone simulator
*  native-base: "^2.4.1",
*  react-native-router-flux: "^3.43.0"

**Comment by Jasbir23** [comment]
@sinevitch You renamed the project in your `package.json`. I can tell from the screenshot above.
You also need to register this name in your `AppRegistry` in your 'index.ios.js'
